name       : librevenge
version    : 0.0.4
release    : 2
source     :
    - http://internode.dl.sourceforge.net/project/libwpd/librevenge/librevenge-0.0.4/librevenge-0.0.4.tar.xz : 933f0729f04267cc354b9a02bc3e9afefa5512a3bdd0b45f159ee14a3e3347b2
license    :
    - LGPL-2.1
    - MPL-2.0
component  : programming
summary    : Library for writing document import filters
description: |
    Librevenge is a base library for writing document import filters. It has interfaces for text documents, vector graphics, spreadsheets and presentations.
builddeps  :
    - pkgconfig(cppunit)
    - libboost-devel
setup      : |
    %configure --disable-werror
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check

